name: pre-commit
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pipenv"
      - run: pip install pipenv
      - run: pipenv install
      - run: pipenv run pre-commit install
      - run: pipenv run pre-commit run --all-files
